name: cttw_selection
description: Une application de sélection de joueurs de tennis de table
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animations: ^2.0.3
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Zen Kaku Gothic Antique
      fonts:
        - asset: fonts/ZenKakuGothicAntique.ttf